<a href="https://colab.research.google.com/github/therudradev/Python_Programming/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔹 What does `axis` mean in NumPy?

👉 Think of `axis` as **the dimension that will collapse / be operated on**.

* `axis=0` → operation happens **down the rows** (vertically), so result is per-column.
* `axis=1` → operation happens **across the columns** (horizontally), so result is per-row.

✅ Example (summing):

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))  # sum down rows → [5 7 9]
print(np.sum(arr, axis=1))  # sum across cols → [6 15]
```

---



✅ **Golden Rule to Remember**

* **axis=0 → rows are affected** (row count can shrink in reductions, or grow in stacking).
* **axis=1 → columns are affected** (column count can shrink in reductions, or grow in stacking).

---

In [2]:
# 🔹 Example 1: 2D Array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# Sum without axis
print(np.sum(arr))   # 21 (sum of all elements)

21


In [4]:
# Sum along axis=0 (column-wise)
print(np.sum(arr, axis=0))   # [5 7 9]

[5 7 9]


In [5]:
arr3d = np.array([[[1, 2],
                   [3, 4]],

                  [[5, 6],
                   [7, 8]]])
print(arr3d.shape)  # (2, 2, 2)

(2, 2, 2)


### Axis meanings:

* **axis=0** → across "blocks"
* **axis=1** → across "rows"
* **axis=2** → across "columns"

In [6]:
# Example:
print(np.sum(arr3d, axis=0))
print()
# [[1 2]      [[5 6]
#  [3 4]]  +   [7 8]]

print(np.sum(arr3d, axis=1))
print()
# Row1: [1 2]
# Row2: [3 4]
# Sum:  [1+3, 2+4] = [4 6]

print(np.sum(arr3d, axis=2))
print()
# Row1: [1 2] → 1+2 = 3
# Row2: [3 4] → 3+4 = 7

[[ 6  8]
 [10 12]]

[[ 4  6]
 [12 14]]

[[ 3  7]
 [11 15]]



# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [7]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [8]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 3,  3, 68,  1],
       [26, 39, 17, 19],
       [ 2, 66, 57, 18],
       [39, 54, 69, 16],
       [96, 67, 56, 99],
       [ 1, 57, 51, 44]])

In [9]:
np.sort(a)[::-1] #[::-1] for desending

array([97, 95, 94, 91, 86, 82, 71, 65, 64, 49, 42, 38, 36, 20,  8])

In [10]:
np.sort(b,axis=0)  #axis=0 for column

array([[ 1,  3, 17,  1],
       [ 2, 39, 51, 16],
       [ 3, 54, 56, 18],
       [26, 57, 57, 19],
       [39, 66, 68, 44],
       [96, 67, 69, 99]])

# np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
# code
print(a,'\n')
np.append(a,200)

[91 97 49  8 95 38 86 20 42 94 64 82 36 65 71] 



array([ 91,  97,  49,   8,  95,  38,  86,  20,  42,  94,  64,  82,  36,
        65,  71, 200])

In [12]:
b
# b.shape

array([[ 3,  3, 68,  1],
       [26, 39, 17, 19],
       [ 2, 66, 57, 18],
       [39, 54, 69, 16],
       [96, 67, 56, 99],
       [ 1, 57, 51, 44]])

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

# np.ones((b.shape[0],1)  means  (6, 1) → same number of rows, one column
# axis=1 means operation across column so result is per-row

array([[ 3.,  3., 68.,  1.,  1.],
       [26., 39., 17., 19.,  1.],
       [ 2., 66., 57., 18.,  1.],
       [39., 54., 69., 16.,  1.],
       [96., 67., 56., 99.,  1.],
       [ 1., 57., 51., 44.,  1.]])

In [14]:
np.append(b,np.ones((1,b.shape[1])),axis=0)

# np.ones((1,b.shape[1]) means (1, 4) → one row, same number of columns
# axis=0 means operation across row so result is per-column

array([[ 3.,  3., 68.,  1.],
       [26., 39., 17., 19.],
       [ 2., 66., 57., 18.],
       [39., 54., 69., 16.],
       [96., 67., 56., 99.],
       [ 1., 57., 51., 44.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[3.00000000e+00, 3.00000000e+00, 6.80000000e+01, 1.00000000e+00,
        2.69964488e-02],
       [2.60000000e+01, 3.90000000e+01, 1.70000000e+01, 1.90000000e+01,
        2.91659439e-01],
       [2.00000000e+00, 6.60000000e+01, 5.70000000e+01, 1.80000000e+01,
        8.07118790e-01],
       [3.90000000e+01, 5.40000000e+01, 6.90000000e+01, 1.60000000e+01,
        8.79666321e-01],
       [9.60000000e+01, 6.70000000e+01, 5.60000000e+01, 9.90000000e+01,
        3.77619043e-01],
       [1.00000000e+00, 5.70000000e+01, 5.10000000e+01, 4.40000000e+01,
        1.27851406e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0) #np.concatenate(a,b,c,d,e,f...)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [19]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [21]:
# code
a.shape

(15,)

In [22]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [23]:
np.expand_dims(a,axis=1)

array([[91],
       [97],
       [49],
       [ 8],
       [95],
       [38],
       [86],
       [20],
       [42],
       [94],
       [64],
       [82],
       [36],
       [65],
       [71]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [24]:
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [25]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  6,  9, 10, 11, 13, 14]),)

In [26]:
# replace all values > 50 with 0
#np.where(condition,true,false)

np.where(a>50,0,a)

array([ 0,  0, 49,  8,  0, 38,  0, 20, 42,  0,  0,  0, 36,  0,  0])

In [27]:
np.where(a%2 == 0,0,a)

array([91, 97, 49,  0, 95,  0,  0,  0,  0,  0,  0,  0,  0, 65, 71])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [28]:
# code
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [29]:
np.argmax(a)

np.int64(1)

In [30]:
b

array([[ 3,  3, 68,  1],
       [26, 39, 17, 19],
       [ 2, 66, 57, 18],
       [39, 54, 69, 16],
       [96, 67, 56, 99],
       [ 1, 57, 51, 44]])

In [31]:
np.argmax(b,axis=0)

array([4, 4, 3, 4])

In [32]:
np.argmax(b,axis=1)

array([2, 1, 1, 2, 3, 1])

In [33]:
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [34]:
# np.argmin
np.argmin(a)

np.int64(3)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [35]:
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [36]:
np.cumsum(a)

array([ 91, 188, 237, 245, 340, 378, 464, 484, 526, 620, 684, 766, 802,
       867, 938])

In [37]:
b

array([[ 3,  3, 68,  1],
       [26, 39, 17, 19],
       [ 2, 66, 57, 18],
       [39, 54, 69, 16],
       [96, 67, 56, 99],
       [ 1, 57, 51, 44]])

In [38]:
np.cumsum(b,axis=1)

array([[  3,   6,  74,  75],
       [ 26,  65,  82, 101],
       [  2,  68, 125, 143],
       [ 39,  93, 162, 178],
       [ 96, 163, 219, 318],
       [  1,  58, 109, 153]])

In [39]:
np.cumsum(b)

array([  3,   6,  74,  75, 101, 140, 157, 176, 178, 244, 301, 319, 358,
       412, 481, 497, 593, 660, 716, 815, 816, 873, 924, 968])

In [40]:
# np.cumprod
np.cumprod(a)

array([                  91,                 8827,               432523,
                    3460184,            328717480,          12491264240,
              1074248724640,       21484974492800,      902368928697600,
          84822679297574400,  5428651475044761600,  2427563184641212416,
       -4841445721464111104, -1099322642104844288, -4264931294605737984])

In [41]:
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [42]:
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [43]:
np.percentile(a,50)

np.float64(65.0)

In [44]:
np.median(a)

np.float64(65.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [45]:
# code
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [46]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [48]:
# code
a


array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [49]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [50]:
# code
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [51]:
np.flip(a)

array([71, 65, 36, 82, 64, 94, 42, 20, 86, 38, 95,  8, 49, 97, 91])

In [52]:
b

array([[ 3,  3, 68,  1],
       [26, 39, 17, 19],
       [ 2, 66, 57, 18],
       [39, 54, 69, 16],
       [96, 67, 56, 99],
       [ 1, 57, 51, 44]])

In [53]:
np.flip(b,axis=1)

array([[ 1, 68,  3,  3],
       [19, 17, 39, 26],
       [18, 57, 66,  2],
       [16, 69, 54, 39],
       [99, 56, 67, 96],
       [44, 51, 57,  1]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [54]:
# code
a

array([91, 97, 49,  8, 95, 38, 86, 20, 42, 94, 64, 82, 36, 65, 71])

In [55]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [56]:
# code
a

array([110, 530,  49,   8,  95,  38,  86,  20,  42,  94,  64,  82,  36,
        65,  71])

In [57]:
np.delete(a,[0,2,4])

array([530,   8,  38,  86,  20,  42,  94,  64,  82,  36,  65,  71])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.intersect1d(m,n)

array([3, 4, 5])

In [60]:
np.setdiff1d(n,m)

array([6, 7])

In [61]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [62]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [63]:
# code
a

array([110, 530,  49,   8,  95,  38,  86,  20,  42,  94,  64,  82,  36,
        65,  71])

In [64]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 49, 25, 75, 38, 75, 25, 42, 75, 64, 75, 36, 65, 71])

In [65]:
# 17. np.swapaxes

In [66]:
# 18. np.uniform

In [67]:
# 19. np.count_nonzero

In [68]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [69]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [70]:

# 25. np.allclose and equals